### ISSUE TITLE
Where is the datasets/download_waymo.py?

### ISSUE THREAD

**Issue by LuPaoPao** [nnanhuang/S3Gaussian#1]
Thank you for your great contribution, but I can't find your file: datasets/download_waymo.py

**Comment by wzzheng** [comment]
Thanks for the question. You can find it [here](https://github.com/NVlabs/EmerNeRF/blob/main/datasets/download_waymo.py). We will update the code.

**Comment by nnanhuang** [comment]
We have already updated the code, thanks for the question!

**Comment by tapowanliwuyun** [comment]
Thank you for your great contribution, I am a beginner, and I encountered an error：
```
Welcome to the Google Cloud CLI! Run "gcloud -h" to get the list of available commands.
---

F:\waymo>python data\download_waymo.py --target_dir ./data/waymo/raw --scene_ids 114 700 754
note: `gcloud auth login` is required before running this script
Downloading Waymo dataset from Google Cloud Storage...
[1/3] Failed to download. Error: [WinError 2] 系统找不到指定的文件。
[2/3] Failed to download. Error: [WinError 2] 系统找不到指定的文件。
[3/3] Failed to download. Error: [WinError 2] 系统找不到指定的文件。
```
How should I consider this kind of issue? I executed this command under Windows.

**Comment by wzzheng** [comment]
Hi,  perhaps you can try modifying the target_dir "./data/waymo/raw" to the directory that you want to put your data in. On windows, it should look like this ".\data\waymo\raw". 
Or, alternatively, you can download the data directly from the [website](https://waymo.com/open/). 
Still, I highly recommend you run our code on Linux instead of Windows. I expect numerous errors ahead of you.

**Comment by james201011071** [comment]
Hi，when extract_and_save_features, descriptors = extractor.extract_descriptors(....) encounters an error : Segmentation Fault.
how can i solve it ? 
@wzzheng

**Comment by LuPaoPao** [comment]
> Segmentation Fault

Same Here~

**Comment by nnanhuang** [comment]
> Hi，when extract_and_save_features, descriptors = extractor.extract_descriptors(....) encounters an error : Segmentation Fault. how can i solve it ? @wzzheng

Hi, the segmentation fault might be caused by a connection issue with Hugging Face's servers when trying to load the DINOv2 model. Consider downloading the model locally to solve this problem.

**Comment by LuPaoPao** [comment]
> > Hi，when extract_and_save_features, descriptors = extractor.extract_descriptors(....) encounters an error : Segmentation Fault. how can i solve it ? @wzzheng
> 
> Hi, the segmentation fault might be caused by a connection issue with Hugging Face's servers when trying to load the DINOv2 model. Consider downloading the model locally to solve this problem.

I re-used the official download of that model (torch automatically downloaded not hugging face). utils/feature_extractor.py there's an error on line 362 _ = self.model(batch), and the tensor goes straight to the model.

**Comment by LuPaoPao** [comment]
> > Hi，when extract_and_save_features, descriptors = extractor.extract_descriptors(....) encounters an error : Segmentation Fault. how can i solve it ? @wzzheng
> 
> Hi, the segmentation fault might be caused by a connection issue with Hugging Face's servers when trying to load the DINOv2 model. Consider downloading the model locally to solve this problem.

I re-used the official download of that model (torch automatically downloaded not hugging face). utils/feature_extractor.py: Line 362 _ = self.model(batch) reports an error. I sent tensor in and the model reported an error.


The model is defined at:
        if "dinov2" in model_type:
            # also supports dinov2+register.
            # dinov2+register still significantly benefits from the our position embedding decomposition!
            model = torch.hub.load("facebookresearch/dinov2", model_type)
        elif "dino" in model_type:
            model = torch.hub.load("facebookresearch/dino:main", model_type)

**Comment by Mr-ind1fferent** [comment]
Thanks for the amazing work! There is something wrong with the code and i do not know where to find it.
python data/download_waymo.py --split_file data/waymo_splits/static32.txt
note: `gcloud auth login` is required before running this script
Downloading Waymo dataset from Google Cloud Storage...
Traceback (most recent call last):
  File "data/download_waymo.py", line 82, in <module>
    total_list = open("data/waymo_train_list.txt", "r").readlines()   
FileNotFoundError: [Errno 2] No such file or directory: 'data/waymo_train_list.txt'

**Comment by wing158** [comment]
可否提供一个百度网盘链接下载运行1-2个测试场景 ，谢谢

**Comment by nnanhuang** [comment]
> Thanks for the amazing work! There is something wrong with the code and i do not know where to find it. python data/download_waymo.py --split_file data/waymo_splits/static32.txt note: `gcloud auth login` is required before running this script Downloading Waymo dataset from Google Cloud Storage... Traceback (most recent call last): File "data/download_waymo.py", line 82, in total_list = open("data/waymo_train_list.txt", "r").readlines() FileNotFoundError: [Errno 2] No such file or directory: 'data/waymo_train_list.txt'

Hi, you need to login  first to download data by gcloud. Maybe download here [here](https://console.cloud.google.com/storage/browser/waymo_open_dataset_scene_flow/train?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=true) manually is more convenient.

**Comment by lziiid** [comment]
> > > Hi，when extract_and_save_features, descriptors = extractor.extract_descriptors(....) encounters an error : Segmentation Fault. how can i solve it ? @wzzheng
> > 
> > 
> > Hi, the segmentation fault might be caused by a connection issue with Hugging Face's servers when trying to load the DINOv2 model. Consider downloading the model locally to solve this problem.
> 
> I re-used the official download of that model (torch automatically downloaded not hugging face). utils/feature_extractor.py: Line 362 _ = self.model(batch) reports an error. I sent tensor in and the model reported an error.
> 
> The model is defined at: if "dinov2" in model_type: # also supports dinov2+register. # dinov2+register still significantly benefits from the our position embedding decomposition! model = torch.hub.load("facebookresearch/dinov2", model_type) elif "dino" in model_type: model = torch.hub.load("facebookresearch/dino:main", model_type)

I meet the same problem. Did you solve this? I have no idea :(

**Comment by 520jz** [comment]
> Thank you for your great contribution, I am a beginner, and I encountered an error：
> 
> ```
> Welcome to the Google Cloud CLI! Run "gcloud -h" to get the list of available commands.
> ---
> 
> F:\waymo>python data\download_waymo.py --target_dir ./data/waymo/raw --scene_ids 114 700 754
> note: `gcloud auth login` is required before running this script
> Downloading Waymo dataset from Google Cloud Storage...
> [1/3] Failed to download. Error: [WinError 2] 系统找不到指定的文件。
> [2/3] Failed to download. Error: [WinError 2] 系统找不到指定的文件。
> [3/3] Failed to download. Error: [WinError 2] 系统找不到指定的文件。
> ```
> 
> How should I consider this kind of issue? I executed this command under Windows.


Hello, have you solved this problem? I encountered the exact same error as you when downloading on Windows, even after modifying the path.
