### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by tapowanliwuyun** [nnanhuang/S3Gaussian#3]
ChatGPT
Hello, thank you for your excellent work! I encountered an issue while running my code. Have you encountered similar problems before?

`
(S3Gaussian) czy@amax:~/3DGS/S3Gaussian$ python train.py -s /home/czy/3DGS/S3Gaussian/data/waymo/processed/training/114 --expname "waymo" --model_path /home/czy/3DGS/S3Gaussian/data/waymo/processed/training/114/output --configs "arguments/nvs.py"

...

Training progress:  60%|███████████████████████████████▏                    | 30000/50000 [1:41:53<1:13:30,  4.53it/s, step=30000, Loss=0.0503969, psnr=24.76, dynamic point=478446, point=885833]
[ITER 30000] Saving Checkpoint [06/06 21:42:51]
Evaluating Test Set Pixels... [06/06 21:42:54]
                                                    /home/czy/3DGS/S3Gaussian/utils/video_utils.py:206: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  dx = torch.tensor(dx)
/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  warnings.warn(
/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/master/lpips/weights/v0.1/alex.pth" to /home/czy/.cache/torch/hub/checkpoints/alex.pth
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.87k/5.87k [00:00<00:00, 2.95MB/s]
/home/czy/3DGS/S3Gaussian/utils/video_utils.py:221: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).                                                                                                                 | 0.00/5.87k [00:00<?, ?B/s]
  lpipss.append(torch.tensor(lpips(rgb, gt_rgb,net_type='alex')).mean().item())
rendering full data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:18<00:00,  1.58s/it]
Eval over 12 images: [06/06 21:43:15]█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:18<00:00,  1.25it/s]
	PSNR: 22.9827 [06/06 21:43:15]
	SSIM: 0.8580 [06/06 21:43:15]
	LPIPS: 0.1811 [06/06 21:43:15]
	Masked PSNR: 16.9044 [06/06 21:43:15]
	Masked SSIM: 0.5869 [06/06 21:43:15]
Image evaluation metrics saved to /home/czy/3DGS/S3Gaussian/data/waymo/processed/training/114/output/eval/metrics/30000_images_test_2024-06-06_19-51-42.json [06/06 21:43:15]
Traceback (most recent call last):
  File "/home/czy/3DGS/S3Gaussian/train.py", line 764, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "/home/czy/3DGS/S3Gaussian/train.py", line 626, in training
    scene_reconstruction(dataset, opt, hyper, pipe, testing_iterations, saving_iterations,
  File "/home/czy/3DGS/S3Gaussian/train.py", line 540, in scene_reconstruction
    do_evaluation(
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/czy/3DGS/S3Gaussian/train.py", line 108, in do_evaluation
    vis_frame_dict = save_videos(
  File "/home/czy/3DGS/S3Gaussian/utils/video_utils.py", line 364, in save_videos
    return_frame = save_seperate_videos(
  File "/home/czy/3DGS/S3Gaussian/utils/video_utils.py", line 490, in save_seperate_videos
    writer.append_data(frames) # [H,W,3]
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 587, in _append_data
    self._initialize()
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 648, in _initialize
    self._write_gen.send(None)
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio_ffmpeg/_io.py", line 508, in write_frames
    codec = get_first_available_h264_encoder()
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio_ffmpeg/_io.py", line 124, in get_first_available_h264_encoder
    compiled_encoders = get_compiled_h264_encoders()
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio_ffmpeg/_io.py", line 58, in get_compiled_h264_encoders
    cmd = [get_ffmpeg_exe(), "-hide_banner", "-encoders"]
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 28, in get_ffmpeg_exe
    exe = _get_ffmpeg_exe()
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 44, in _get_ffmpeg_exe
    exe = os.path.join(_get_bin_dir(), FNAME_PER_PLATFORM.get(plat, ""))
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 69, in _get_bin_dir
    ref = importlib.resources.files("imageio_ffmpeg.binaries") / "__init__.py"
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/importlib/_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/czy/anaconda3/envs/S3Gaussian/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Training progress:  60%|███████████████████████████████▏                    | 30000/50000 [1:42:17<1:08:11,  4.89it/s, step=30000, Loss=0.0503969, psnr=24.76, dynamic point=478446, point=885833]
`

**Comment by JJho1314** [comment]
I'm having the same issue, also with an error at 30,000 iterations

**Comment by tapowanliwuyun** [comment]
> I'm having the same issue, also with an error at 30,000 iterations

Have you resolved it now?
